In [1]:
import requests
import pandas as pd
import json
import time

In [2]:
metro_areas= requests.get('https://api.datausa.io/attrs/geo/?sumlevel=msa').json()
metro_areas = metro_areas['data']

In [3]:
metro_names={}
for data in metro_areas:
    metro_names[data[8]]=data[9]

In [4]:
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36'}
pop=requests.get('http://db.datausa.io/api/?show=geo&sumlevel=msa&required=pop&year=all',headers=headers).json()['data']
for i in pop:
    if i[1] in metro_names.keys():
        i.append(metro_names[i[1]])

In [5]:
dfpop=pd.DataFrame(pop,columns=['Year','Code','Population','Place'])
dfnames=dfpop.sort_values(by=['Year','Population']).tail(10)
dfnames.reset_index()

,index,Year,Code,Population,Place
0,2895,2016,31000US14460,4728844,"Boston-Cambridge-Newton, MA-NH Metro Area"
1,2836,2016,31000US12060,5612777,"Atlanta-Sandy Springs-Roswell, GA Metro Area"
2,3345,2016,31000US33100,5926955,"Miami-Fort Lauderdale-West Palm Beach, FL Metr..."
3,3691,2016,31000US47900,6011752,"Washington-Arlington-Alexandria, DC-VA-MD-WV"
4,3461,2016,31000US37980,6047721,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD"
5,3181,2016,31000US26420,6482592,"Houston-The Woodlands-Sugar Land, TX Metro Area"
6,3004,2016,31000US19100,6957123,"Dallas-Fort Worth-Arlington, TX"
7,2954,2016,31000US16980,9528396,"Chicago-Naperville-Elgin, IL-IN-WI Metro Area"
8,3293,2016,31000US31080,13189366,"Los Angeles-Long Beach-Anaheim, CA Metro Area"
9,3403,2016,31000US35620,20031443,"New York-Newark-Jersey City, NY-NJ-PA Metro Area"

In [6]:
mpv=requests.get('https://db.datausa.io/api/?show=geo&sumlevel=msa&required=median_property_value&year=all',headers=headers).json()['data']
commute_time=requests.get('https://datausa.io/api/data?measure=Average Commute Time&drilldowns=MSA',headers=headers).json()['data']

In [7]:
commute_mode={}
poverty={}
ownership={}
income={}
age={}
property_tax={}
citizen={}
local={}
for i in range(10):
    commute_mode[dfnames.iloc[i]['Place']]=requests.get('https://datausa.io/api/data?measure=Commute%20Means,Commute%20Means%20Moe&geo='+dfnames.iloc[i]['Code']+'&drilldowns=Group',headers=headers).json()['data']
    time.sleep(5)
    poverty[dfnames.iloc[i]['Place']]=requests.get('https://datausa.io/api/data?Geography='+dfnames.iloc[i]['Code'] +'&measure=Poverty%20Population,Poverty%20Population%20Moe&Poverty%20Status=0',headers=headers).json()['data']
    time.sleep(5)
    ownership[dfnames.iloc[i]['Place']]=requests.get('https://datausa.io/api/data?measure=Household%20Ownership,Household%20Ownership%20Moe&Geography='+dfnames.iloc[i]['Code']+'&drilldowns=Occupied%20By',headers=headers).json()['data']
    time.sleep(5)
    income[dfnames.iloc[i]['Place']]=requests.get('https://datausa.io/api/data?Geography='+dfnames.iloc[i]['Code']+'&measure=Total%20Population,Total%20Population%20MOE%20Appx,Record%20Count&drilldowns=Wage%20Bin&Workforce%20Status=true&Record%20Count%3E=5',headers=headers).json()['data']
    time.sleep(5)
    age[dfnames.iloc[i]['Place']]=requests.get('https://datausa.io/api/data?Geography='+dfnames.iloc[i]['Code']+'&measures=Birthplace,Birthplace%20Moe&drilldowns=Place%20of%20Birth,Age',headers=headers).json()['data']
    time.sleep(5)
    property_tax[dfnames.iloc[i]['Place']]=requests.get('https://datausa.io/api/data?measure=Real%20Estate%20Taxes%20by%20Mortgage,Real%20Estate%20Taxes%20by%20Mortgage%20Moe&drilldowns=Real%20Estate%20Taxes%20Paid&geo='+dfnames.iloc[i]['Code'],headers=headers).json()['data']
    time.sleep(5)
    citizen[dfnames.iloc[i]['Place']]=requests.get('https://datausa.io/api/data?measure=Citizenship%20Status&drilldowns=Citizenship&Geography='+dfnames.iloc[i]['Code'],headers=headers).json()['data']
    time.sleep(5)
    local[dfnames.iloc[i]['Place']]=requests.get('https://datausa.io/api/data?measure=Foreign-Born%20Citizens,Population&Geography='+dfnames.iloc[i]['Code'],headers=headers).json()['data']

In [157]:
dfcommute_mode=None
#convert commute mode data from dictionaries to data frame
for name in commute_mode:
    for i in range(45):
        dfcommute_mode=pd.concat([dfcommute_mode, pd.DataFrame.from_dict(commute_mode[name][i],orient='index').T ])
#remove extra columns
dfcommute_mode=dfcommute_mode.drop('ID Geography',axis=1)
dfcommute_mode=dfcommute_mode.drop('Slug Geography',axis=1)
dfcommute_mode=dfcommute_mode.drop('ID Year',axis=1)
#reindex by location and year
dfcommute_mode=dfcommute_mode.set_index(['Geography','Year'])
dfcommute_mode

                                           ID Group           Group  \
Geography                             Year
Boston-Cambridge-Newton, MA-NH        2017        2  Public Transit
                                      2017        8  Worked At Home
                                      2017        0     Drove Alone
                                      2017        4      Motorcycle
                                      2017        5         Bicycle
                                      2017        1       Carpooled
                                      2017        7           Other
                                      2017        3            Taxi
                                      2017        6          Walked
                                      2016        0     Drove Alone
                                      2016        2  Public Transit
                                      2016        3            Taxi
                                      2016        7           Other
                                      2016        6          Walked
                                      2016        1       Carpooled
                                      2016        4      Motorcycle
                                      2016        8  Worked At Home
                                      2016        5         Bicycle
                                      2015        1       Carpooled
                                      2015        2  Public Transit
                                      2015        0     Drove Alone
                                      2015        6          Walked
                                      2015        4      Motorcycle
                                      2015        7           Other
                                      2015        8  Worked At Home
                                      2015        3            Taxi
                                      2015        5         Bicycle
                                      2014        7           Other
                                      2014        5         Bicycle
                                      2014        0     Drove Alone
...                                             ...             ...
New York-Newark-Jersey City, NY-NJ-PA 2016        4      Motorcycle
                                      2016        8  Worked At Home
                                      2016        5         Bicycle
                                      2015        1       Carpooled
                                      2015        2  Public Transit
                                      2015        0     Drove Alone
                                      2015        6          Walked
                                      2015        4      Motorcycle
                                      2015        7           Other
                                      2015        8  Worked At Home
                                      2015        3            Taxi
                                      2015        5         Bicycle
                                      2014        7           Other
                                      2014        5         Bicycle
                                      2014        0     Drove Alone
                                      2014        1       Carpooled
                                      2014        6          Walked
                                      2014        4      Motorcycle
                                      2014        8  Worked At Home
                                      2014        3            Taxi
                                      2014        2  Public Transit
                                      2013        5         Bicycle
                                      2013        3            Taxi
                                      2013        7           Other
                                      2013        2  Public Transit
                                      2013        8  Worked At Home
                                      2013        4      Motorcycle
                                      2013        6          Walked
                                      2013        1       Carpooled
                                      2013        0     Drove Alone

                                           Commute Means Commute Means Moe
Geography                             Year
Boston-Cambridge-Newton, MA-NH        2017        345532           10260.1
                                      2017        137506              6726
                                      2017       1712805             17778
                                      2017          1877               604
                                      2017         27475              2690
                                      2017        180758           8805.91
                                      2017         24395              3324
                                      2017          7605              1675
                                      2017        134501              6022
                                      2016       1690471             15000
                                      2016        333224           11095.1
                                      2016          7964              1666
                                      2016         26295              2760
                                      2016        131231              5018
                                      2016        191244           8244.76
                                      2016          1518               645
                                      2016        131590              6249
                                      2016         25953              2700
                                      2015        176374           8507.99
                                      2015        341031           9953.13
                                      2015       1671144             16152
                                      2015        139092              5679
                                      2015          2505               725
                                      2015         21801              2649
                                      2015        121594              5640
                                      2015          5476              1250
                                      2015         22950              2763
                                      2014         21243              2287
                                      2014         24222              2241
                                      2014       1647579             15745
...                                                  ...               ...
New York-Newark-Jersey City, NY-NJ-PA 2016          7125              1514
                                      2016        435350             13775
                                      2016         64222              4110
                                      2015        605205           16336.7
                                      2015       3019575             28975
                                      2015       4780304             30568
                                      2015        584725             16064
                                      2015          4833               895
                                      2015         68905              5372
                                      2015        397207             10279
                                      2015         61129              6311
                                      2015         61947              5134
                                      2014         85623              6220
                                      2014         56644              4893
                                      2014       4758846             26331
                                      2014        609631           13697.5
                                      2014        568385             14383
                                      2014          4461              1070
                                      2014        395733             12316
                                      2014         54146              4730
                                      2014       2944842           25848.8
                                      2013         60215              5324
                                      2013         55065              4688
                                      2013         78232              5445
                                      2013       2862178           27570.4
                                      2013        386391             11616
                                      2013          6017              1172
                                      2013        548279             13995
                                      2013        628428           15505.4
                                      2013       4649744             28111

[450 rows x 4 columns]

In [105]:
dfpoverty=None
for name in poverty:
    for i in range(5):
        dfpoverty=pd.concat([dfpoverty, pd.DataFrame.from_dict(poverty[name][i],orient='index').T ])
dfpoverty=dfpoverty.drop('ID Geography',axis=1)
dfpoverty=dfpoverty.drop('Slug Geography',axis=1)
dfpoverty=dfpoverty.drop('ID Year',axis=1)
#reindex by location and year
dfpoverty=dfpoverty.set_index(['Geography','Year'])
dfpoverty

                                           ID Group           Group  \
Geography                             Year
Boston-Cambridge-Newton, MA-NH        2017        2  Public Transit
                                      2017        8  Worked At Home
                                      2017        0     Drove Alone
                                      2017        4      Motorcycle
                                      2017        5         Bicycle
                                      2017        1       Carpooled
                                      2017        7           Other
                                      2017        3            Taxi
                                      2017        6          Walked
                                      2016        0     Drove Alone
                                      2016        2  Public Transit
                                      2016        3            Taxi
                                      2016        7           Other
                                      2016        6          Walked
                                      2016        1       Carpooled
                                      2016        4      Motorcycle
                                      2016        8  Worked At Home
                                      2016        5         Bicycle
                                      2015        1       Carpooled
                                      2015        2  Public Transit
                                      2015        0     Drove Alone
                                      2015        6          Walked
                                      2015        4      Motorcycle
                                      2015        7           Other
                                      2015        8  Worked At Home
                                      2015        3            Taxi
                                      2015        5         Bicycle
                                      2014        7           Other
                                      2014        5         Bicycle
                                      2014        0     Drove Alone
...                                             ...             ...
New York-Newark-Jersey City, NY-NJ-PA 2016        4      Motorcycle
                                      2016        8  Worked At Home
                                      2016        5         Bicycle
                                      2015        1       Carpooled
                                      2015        2  Public Transit
                                      2015        0     Drove Alone
                                      2015        6          Walked
                                      2015        4      Motorcycle
                                      2015        7           Other
                                      2015        8  Worked At Home
                                      2015        3            Taxi
                                      2015        5         Bicycle
                                      2014        7           Other
                                      2014        5         Bicycle
                                      2014        0     Drove Alone
                                      2014        1       Carpooled
                                      2014        6          Walked
                                      2014        4      Motorcycle
                                      2014        8  Worked At Home
                                      2014        3            Taxi
                                      2014        2  Public Transit
                                      2013        5         Bicycle
                                      2013        3            Taxi
                                      2013        7           Other
                                      2013        2  Public Transit
                                      2013        8  Worked At Home
                                      2013        4      Motorcycle
                                      2013        6          Walked
                                      2013        1       Carpooled
                                      2013        0     Drove Alone

                                           Commute Means Commute Means Moe
Geography                             Year
Boston-Cambridge-Newton, MA-NH        2017        345532           10260.1
                                      2017        137506              6726
                                      2017       1712805             17778
                                      2017          1877               604
                                      2017         27475              2690
                                      2017        180758           8805.91
                                      2017         24395              3324
                                      2017          7605              1675
                                      2017        134501              6022
                                      2016       1690471             15000
                                      2016        333224           11095.1
                                      2016          7964              1666
                                      2016         26295              2760
                                      2016        131231              5018
                                      2016        191244           8244.76
                                      2016          1518               645
                                      2016        131590              6249
                                      2016         25953              2700
                                      2015        176374           8507.99
                                      2015        341031           9953.13
                                      2015       1671144             16152
                                      2015        139092              5679
                                      2015          2505               725
                                      2015         21801              2649
                                      2015        121594              5640
                                      2015          5476              1250
                                      2015         22950              2763
                                      2014         21243              2287
                                      2014         24222              2241
                                      2014       1647579             15745
...                                                  ...               ...
New York-Newark-Jersey City, NY-NJ-PA 2016          7125              1514
                                      2016        435350             13775
                                      2016         64222              4110
                                      2015        605205           16336.7
                                      2015       3019575             28975
                                      2015       4780304             30568
                                      2015        584725             16064
                                      2015          4833               895
                                      2015         68905              5372
                                      2015        397207             10279
                                      2015         61129              6311
                                      2015         61947              5134
                                      2014         85623              6220
                                      2014         56644              4893
                                      2014       4758846             26331
                                      2014        609631           13697.5
                                      2014        568385             14383
                                      2014          4461              1070
                                      2014        395733             12316
                                      2014         54146              4730
                                      2014       2944842           25848.8
                                      2013         60215              5324
                                      2013         55065              4688
                                      2013         78232              5445
                                      2013       2862178           27570.4
                                      2013        386391             11616
                                      2013          6017              1172
                                      2013        548279             13995
                                      2013        628428           15505.4
                                      2013       4649744             28111

[450 rows x 4 columns]

In [121]:
dfownership=None
for name in ownership:
    for i in range(10):
        dfownership=pd.concat([dfownership, pd.DataFrame.from_dict(ownership[name][i],orient='index').T ])
dfownership=dfownership.drop('ID Geography',axis=1)
dfownership=dfownership.drop('Slug Geography',axis=1)
dfownership=dfownership.drop('ID Year',axis=1)
#reindex by location and year
dfownership=dfownership.set_index(['Geography','Year'])
dfownership

                                               ID Occupied By  \
Geography                                 Year
Boston-Cambridge-Newton, MA-NH            2017              0
                                          2017              1
                                          2016              0
                                          2016              1
                                          2015              0
                                          2015              1
                                          2014              0
                                          2014              1
                                          2013              0
                                          2013              1
Atlanta-Sandy Springs-Roswell, GA         2017              0
                                          2017              1
                                          2016              0
                                          2016              1
                                          2015              0
                                          2015              1
                                          2014              0
                                          2014              1
                                          2013              0
                                          2013              1
Miami-Fort Lauderdale-West Palm Beach, FL 2017              0
                                          2017              1
                                          2016              0
                                          2016              1
                                          2015              0
                                          2015              1
                                          2014              0
                                          2014              1
                                          2013              0
                                          2013              1
...                                                       ...
Chicago-Naperville-Elgin, IL-IN-WI        2017              0
                                          2017              1
                                          2016              0
                                          2016              1
                                          2015              0
                                          2015              1
                                          2014              0
                                          2014              1
                                          2013              0
                                          2013              1
Los Angeles-Long Beach-Anaheim, CA        2017              0
                                          2017              1
                                          2016              0
                                          2016              1
                                          2015              0
                                          2015              1
                                          2014              0
                                          2014              1
                                          2013              0
                                          2013              1
New York-Newark-Jersey City, NY-NJ-PA     2017              0
                                          2017              1
                                          2016              0
                                          2016              1
                                          2015              0
                                          2015              1
                                          2014              0
                                          2014              1
                                          2013              0
                                          2013              1

                                                    Occupied By  \
Geography                                 Year
Boston-Cambridge-Newton, MA-NH            2017   Owner Occupied
                                          2017  Renter Occupied
                                          2016   Owner Occupied
                                          2016  Renter Occupied
                                          2015   Owner Occupied
                                          2015  Renter Occupied
                                          2014   Owner Occupied
                                          2014  Renter Occupied
                                          2013   Owner Occupied
                                          2013  Renter Occupied
Atlanta-Sandy Springs-Roswell, GA         2017   Owner Occupied
                                          2017  Renter Occupied
                                          2016   Owner Occupied
                                          2016  Renter Occupied
                                          2015   Owner Occupied
                                          2015  Renter Occupied
                                          2014   Owner Occupied
                                          2014  Renter Occupied
                                          2013   Owner Occupied
                                          2013  Renter Occupied
Miami-Fort Lauderdale-West Palm Beach, FL 2017   Owner Occupied
                                          2017  Renter Occupied
                                          2016   Owner Occupied
                                          2016  Renter Occupied
                                          2015   Owner Occupied
                                          2015  Renter Occupied
                                          2014   Owner Occupied
                                          2014  Renter Occupied
                                          2013   Owner Occupied
                                          2013  Renter Occupied
...                                                         ...
Chicago-Naperville-Elgin, IL-IN-WI        2017   Owner Occupied
                                          2017  Renter Occupied
                                          2016   Owner Occupied
                                          2016  Renter Occupied
                                          2015   Owner Occupied
                                          2015  Renter Occupied
                                          2014   Owner Occupied
                                          2014  Renter Occupied
                                          2013   Owner Occupied
                                          2013  Renter Occupied
Los Angeles-Long Beach-Anaheim, CA        2017   Owner Occupied
                                          2017  Renter Occupied
                                          2016   Owner Occupied
                                          2016  Renter Occupied
                                          2015   Owner Occupied
                                          2015  Renter Occupied
                                          2014   Owner Occupied
                                          2014  Renter Occupied
                                          2013   Owner Occupied
                                          2013  Renter Occupied
New York-Newark-Jersey City, NY-NJ-PA     2017   Owner Occupied
                                          2017  Renter Occupied
                                          2016   Owner Occupied
                                          2016  Renter Occupied
                                          2015   Owner Occupied
                                          2015  Renter Occupied
                                          2014   Owner Occupied
                                          2014  Renter Occupied
                                          2013   Owner Occupied
                                          2013  Renter Occupied

                                               Household Ownership  \
Geography                                 Year
Boston-Cambridge-Newton, MA-NH            2017             1127376
                                          2017              695658
                                          2016             1106093
                                          2016              697176
                                          2015             1090903
                                          2015              691752
                                          2014             1087964
                                          2014              689853
                                          2013             1070637
                                          2013              692800
Atlanta-Sandy Springs-Roswell, GA         2017             1323423
                                          2017              778722
                                          2016             1264846
                                          2016              797952
                                          2015             1248726
                                          2015              779979
                                          2014             1236658
                                          2014              744789
                                          2013             1237449
                                          2013              716899
Miami-Fort Lauderdale-West Palm Beach, FL 2017             1252164
                                          2017              853714
                                          2016             1223752
                                          2016              874934
                                          2015             1215228
                                          2015              862134
                                          2014             1219261
                                          2014              828064
                                          2013             1233136
                                          2013              799302
...                                                            ...
Chicago-Naperville-Elgin, IL-IN-WI        2017             2245904
                                          2017             1242408
                                          2016             2213958
                                          2016             1277677
                                          2015             2195149
                                          2015             1275844
                                          2014             2202845
                                          2014             1239329
                                          2013             2211699
                                          2013             1238632
Los Angeles-Long Beach-Anaheim, CA        2017             2105484
                                          2017             2243059
                                          2016             2058153
                                          2016             2279654
                                          2015             2065358
                                          2015             2250279
                                          2014             2071774
                                          2014             2216200
                                          2013             2055136
                                          2013             2196359
New York-Newark-Jersey City, NY-NJ-PA     2017             3733949
                                          2017             3470851
                                          2016             3633552
                                          2016             3484472
                                          2015             3621498
                                          2015             3503567
                                          2014             3627096
                                          2014             3525664
                                          2013             3655346
                                          2013             3425345

                                               Household Ownership Moe
Geography                                 Year
Boston-Cambridge-Newton, MA-NH            2017                    9935
                                          2017                    9661
                                          2016                    9122
                                          2016                   10532
                                          2015                   10765
                                          2015                   11382
                                          2014                    9797
                                          2014                   10674
                                          2013                   10448
                                          2013                   10753
Atlanta-Sandy Springs-Roswell, GA         2017                   12765
                                          2017                   13055
                                          2016                   14328
                                          2016                   13287
                                          2015                   13043
                                          2015                   12847
                                          2014                   12105
                                          2014                   11717
                                          2013                   12058
                                          2013                   11472
Miami-Fort Lauderdale-West Palm Beach, FL 2017                   11841
                                          2017                   10857
                                          2016                   12899
                                          2016                   11966
                                          2015                   11643
                                          2015                   10903
                                          2014                   11483
                                          2014                   10872
                                          2013                   12581
                                          2013                   10098
...                                                                ...
Chicago-Naperville-Elgin, IL-IN-WI        2017                   13960
                                          2017                   14116
                                          2016                   15427
                                          2016                   15901
                                          2015                   10507
                                          2015                   13407
                                          2014                   11995
                                          2014                   13406
                                          2013                   14111
                                          2013                   13926
Los Angeles-Long Beach-Anaheim, CA        2017                   14650
                                          2017                   17146
                                          2016                   11849
                                          2016                   11575
                                          2015                   14598
                                          2015                   15104
                                          2014                   14907
                                          2014                   15120
                                          2013                   16422
                                          2013                   15847
New York-Newark-Jersey City, NY-NJ-PA     2017                   20321
                                          2017                   20019
                                          2016                   20367
                                          2016                   22854
                                          2015                   20212
                                          2015                   18091
                                          2014                   20213
                                          2014                   21497
                                          2013                   19946
                                          2013                   19421

[100 rows x 4 columns]

In [135]:
dfincome=None
for name in income:
    for i in range(84):
        dfincome=pd.concat([dfincome, pd.DataFrame.from_dict(income[name][i],orient='index').T ])
dfincome=dfincome.drop('ID Geography',axis=1)
#dfincome=dfincome.drop('Slug Geography',axis=1)
dfincome=dfincome.drop('ID Year',axis=1)
#reindex by location and year
dfincome=dfincome.set_index(['Geography','Year'])
dfincome

                   ID Wage Bin   Wage Bin ID Workforce Status  \
Geography     Year
Massachusetts 2017          16  $150-160k                True
              2017          21     $200k+                True
              2017          20  $190-200k                True
              2017           2    $10-20k                True
              2017          19  $180-190k                True
              2017           3    $20-30k                True
              2017          18  $170-180k                True
              2017           4    $30-40k                True
              2017          17  $160-170k                True
              2017           5    $40-50k                True
              2017           1     < $10K                True
              2017           6    $50-60k                True
              2017          15  $140-150k                True
              2017           7    $60-70k                True
              2017          14  $130-140k                True
              2017           8    $70-80k                True
              2017          13  $120-130k                True
              2017           9    $80-90k                True
              2017          12  $110-120k                True
              2017          10   $90-100k                True
              2017          11  $100-110k                True
              2016           3    $20-30k                True
              2016           6    $50-60k                True
              2016           1     < $10K                True
              2016          16  $150-160k                True
              2016          19  $180-190k                True
              2016           7    $60-70k                True
              2016           2    $10-20k                True
              2016          15  $140-150k                True
              2016           4    $30-40k                True
...                        ...        ...                 ...
New York      2015           4    $30-40k                True
              2015           8    $70-80k                True
              2015          18  $170-180k                True
              2015          15  $140-150k                True
              2015           5    $40-50k                True
              2015           7    $60-70k                True
              2015          17  $160-170k                True
              2015          16  $150-160k                True
              2015          11  $100-110k                True
              2014          14  $130-140k                True
              2014           7    $60-70k                True
              2014          16  $150-160k                True
              2014           6    $50-60k                True
              2014           8    $70-80k                True
              2014          18  $170-180k                True
              2014          15  $140-150k                True
              2014           5    $40-50k                True
              2014           9    $80-90k                True
              2014          19  $180-190k                True
              2014          17  $160-170k                True
              2014           4    $30-40k                True
              2014          10   $90-100k                True
              2014          20  $190-200k                True
              2014          13  $120-130k                True
              2014           3    $20-30k                True
              2014          11  $100-110k                True
              2014          21     $200k+                True
              2014          12  $110-120k                True
              2014           2    $10-20k                True
              2014           1     < $10K                True

                   Workforce Status Total Population  \
Geography     Year
Massachusetts 2017             true            47114
              2017             true           137253
              2017             true             8913
              2017             true           327893
              2017             true            15946
              2017             true           356285
              2017             true            22913
              2017             true           366459
              2017             true            22881
              2017             true           319135
              2017             true           399295
              2017             true           293255
              2017             true            33501
              2017             true           264083
              2017             true            50642
              2017             true           206986
              2017             true            70784
              2017             true           167691
              2017             true            65940
              2017             true           108994
              2017             true           130303
              2016             true           359395
              2016             true           297513
              2016             true           400060
              2016             true            40761
              2016             true            14002
              2016             true           245187
              2016             true           367942
              2016             true            31623
              2016             true           375443
...                             ...              ...
New York      2015             true          1092213
              2015             true           459702
              2015             true            35785
              2015             true            56627
              2015             true           882680
              2015             true           603716
              2015             true            39677
              2015             true            90337
              2015             true           274918
              2014             true            70336
              2014             true           575108
              2014             true            80863
              2014             true           735844
              2014             true           444023
              2014             true            29904
              2014             true            53923
              2014             true           879653
              2014             true           369575
              2014             true            27826
              2014             true            35916
              2014             true          1053653
              2014             true           231120
              2014             true            15565
              2014             true           136415
              2014             true          1188829
              2014             true           262121
              2014             true           277208
              2014             true           109797
              2014             true          1238956
              2014             true          1096715

                   Total Population MOE Appx Record Count
Geography     Year
Massachusetts 2017                   5292.18          475
              2017                    8911.1         1555
              2017                   2314.83           99
              2017                   13366.9         3016
              2017                   3093.03          170
              2017                   13869.4         3178
              2017                   3703.86          251
              2017                   14042.6         3399
              2017                   3701.29          268
              2017                   13205.8         3066
              2017                   14579.1         4302
              2017                   12711.8         2908
              2017                   4471.61          369
              2017                   12119.2         2579
              2017                   5483.87          495
              2017                   10826.1         2108
              2017                   6463.92          771
              2017                   9803.93         1763
              2017                   6243.34          673
              2017                   7975.08         1164
              2017                   8691.75         1337
              2016                   13915.2         3259
              2016                   12789.5         2938
              2016                   14582.3         4329
              2016                   4926.82          451
              2016                   2899.14          162
              2016                   11708.4         2432
              2016                   14059.8         3369
              2016                   4345.48          336
              2016                   14184.7         3398
...                                      ...          ...
New York      2015                   24049.5        10123
              2015                     16215         4564
              2015                    4635.1          325
              2015                   5823.91          556
              2015                   21904.8         8532
              2015                   18424.6         6006
              2015                    4879.6          374
              2015                   7342.01          830
              2015                   12674.6         2663
              2014                    6485.5          693
              2014                     18008         5611
              2014                   6949.77          770
              2014                   20172.4         7285
              2014                   15947.1         4390
              2014                   4238.48          306
              2014                   5683.87          495
              2014                   21860.9         8543
              2014                   14612.7         3532
              2014                   4089.04          288
              2014                   4643.46          340
              2014                     23665         9965
              2014                     11649         2282
              2014                   3060.34          153
              2014                   8998.22         1342
              2014                   24920.1        10855
              2014                   12383.5         2569
              2014                   12723.8         2631
              2014                   8084.97         1075
              2014                   25357.4        11302
              2014                   24077.5        11232

[840 rows x 7 columns]

In [148]:
dfage=None
for name in age:
    for i in range(220):
        dfage=pd.concat([dfage, pd.DataFrame.from_dict(age[name][i],orient='index').T ])
dfage=dfage.drop('ID Geography',axis=1)
dfage=dfage.drop('Slug Geography',axis=1)
dfage=dfage.drop('ID Year',axis=1)
#reindex by location and year
dfage=dfage.set_index(['Geography','Year'])
dfage

                                           ID Place of Birth  \
Geography                             Year
Boston-Cambridge-Newton, MA-NH        2017                 2
                                      2017                 3
                                      2017                 3
                                      2017                 0
                                      2017                 3
                                      2017                 0
                                      2017                 3
                                      2017                 0
                                      2017                 3
                                      2017                 0
                                      2017                 3
                                      2017                 0
                                      2017                 3
                                      2017                 0
                                      2017                 3
                                      2017                 0
                                      2017                 3
                                      2017                 0
                                      2017                 3
                                      2017                 0
                                      2017                 3
                                      2017                 0
                                      2017                 0
                                      2017                 1
                                      2017                 2
                                      2017                 1
                                      2017                 2
                                      2017                 1
                                      2017                 2
                                      2017                 1
...                                                      ...
New York-Newark-Jersey City, NY-NJ-PA 2013                 3
                                      2013                 0
                                      2013                 1
                                      2013                 2
                                      2013                 2
                                      2013                 3
                                      2013                 1
                                      2013                 0
                                      2013                 1
                                      2013                 2
                                      2013                 3
                                      2013                 0
                                      2013                 2
                                      2013                 1
                                      2013                 0
                                      2013                 3
                                      2013                 3
                                      2013                 1
                                      2013                 0
                                      2013                 2
                                      2013                 3
                                      2013                 1
                                      2013                 3
                                      2013                 1
                                      2013                 0
                                      2013                 3
                                      2013                 1
                                      2013                 2
                                      2013                 3
                                      2013                 2

                                                                      Place of Birth  \
Geography                             Year
Boston-Cambridge-Newton, MA-NH        2017    Native; Born Outside The United States
                                      2017                              Foreign Born
                                      2017                              Foreign Born
                                      2017                Born In State of Residence
                                      2017                              Foreign Born
                                      2017                Born In State of Residence
                                      2017                              Foreign Born
                                      2017                Born In State of Residence
                                      2017                              Foreign Born
                                      2017                Born In State of Residence
                                      2017                              Foreign Born
                                      2017                Born In State of Residence
                                      2017                              Foreign Born
                                      2017                Born In State of Residence
                                      2017                              Foreign Born
                                      2017                Born In State of Residence
                                      2017                              Foreign Born
                                      2017                Born In State of Residence
                                      2017                              Foreign Born
                                      2017                Born In State of Residence
                                      2017                              Foreign Born
                                      2017                Born In State of Residence
                                      2017                Born In State of Residence
                                      2017  Born In Other State In The United States
                                      2017    Native; Born Outside The United States
                                      2017  Born In Other State In The United States
                                      2017    Native; Born Outside The United States
                                      2017  Born In Other State In The United States
                                      2017    Native; Born Outside The United States
                                      2017  Born In Other State In The United States
...                                                                              ...
New York-Newark-Jersey City, NY-NJ-PA 2013                              Foreign Born
                                      2013                Born In State of Residence
                                      2013  Born In Other State In The United States
                                      2013    Native; Born Outside The United States
                                      2013    Native; Born Outside The United States
                                      2013                              Foreign Born
                                      2013  Born In Other State In The United States
                                      2013                Born In State of Residence
                                      2013  Born In Other State In The United States
                                      2013    Native; Born Outside The United States
                                      2013                              Foreign Born
                                      2013                Born In State of Residence
                                      2013    Native; Born Outside The United States
                                      2013  Born In Other State In The United States
                                      2013                Born In State of Residence
                                      2013                              Foreign Born
                                      2013                              Foreign Born
                                      2013  Born In Other State In The United States
                                      2013                Born In State of Residence
                                      2013    Native; Born Outside The United States
                                      2013                              Foreign Born
                                      2013  Born In Other State In The United States
                                      2013                              Foreign Born
                                      2013  Born In Other State In The United States
                                      2013                Born In State of Residence
                                      2013                              Foreign Born
                                      2013  Born In Other State In The United States
                                      2013    Native; Born Outside The United States
                                      2013                              Foreign Born
                                      2013    Native; Born Outside The United States

                                           ID Age              Age Birthplace  \
Geography                             Year
Boston-Cambridge-Newton, MA-NH        2017     10  75 Years & Over       5563
                                      2017     10  75 Years & Over      57974
                                      2017      9   65 to 74 Years      74232
                                      2017      1    5 to 17 Years     553566
                                      2017      8   62 to 64 Years      31993
                                      2017      2   18 to 24 Years     272151
                                      2017      7    60 & 61 Years      24421
                                      2017      3   25 to 34 Years     343089
                                      2017      6   55 to 59 Years      71284
                                      2017      4   35 to 44 Years     241914
                                      2017      5   45 to 54 Years     158703
                                      2017      5   45 to 54 Years     314805
                                      2017      4   35 to 44 Years     189549
                                      2017      6   55 to 59 Years     170292
                                      2017      3   25 to 34 Years     174332
                                      2017      7    60 & 61 Years      67246
                                      2017      2   18 to 24 Years      79057
                                      2017      8   62 to 64 Years      85805
                                      2017      1    5 to 17 Years      51260
                                      2017      9   65 to 74 Years     223350
                                      2017      0    Under 5 Years       7982
                                      2017     10  75 Years & Over     173704
                                      2017      0    Under 5 Years     224311
                                      2017      0    Under 5 Years      21194
                                      2017      9   65 to 74 Years       7959
                                      2017      1    5 to 17 Years      87824
                                      2017      8   62 to 64 Years       3014
                                      2017      2   18 to 24 Years     128095
                                      2017      7    60 & 61 Years       2841
                                      2017      3   25 to 34 Years     189132
...                                           ...              ...        ...
New York-Newark-Jersey City, NY-NJ-PA 2013      5   45 to 54 Years    1108324
                                      2013     10  75 Years & Over     551162
                                      2013      9   65 to 74 Years     294001
                                      2013      9   65 to 74 Years      80531
                                      2013      3   25 to 34 Years      61164
                                      2013      6   55 to 59 Years     474543
                                      2013      5   45 to 54 Years     424752
                                      2013      8   62 to 64 Years     275834
                                      2013      2   18 to 24 Years     221720
                                      2013     10  75 Years & Over      61735
                                      2013      7    60 & 61 Years     159457
                                      2013      5   45 to 54 Years    1278174
                                      2013      4   35 to 44 Years      57196
                                      2013     10  75 Years & Over     257379
                                      2013      4   35 to 44 Years    1115674
                                      2013      8   62 to 64 Years     224984
                                      2013      0    Under 5 Years      32854
                                      2013      6   55 to 59 Years     206823
                                      2013      1    5 to 17 Years    2612230
                                      2013      5   45 to 54 Years      83027
                                      2013      9   65 to 74 Years     510599
                                      2013      0    Under 5 Years      70767
                                      2013      1    5 to 17 Years     259702
                                      2013      3   25 to 34 Years     480547
                                      2013      7    60 & 61 Years     209681
                                      2013     10  75 Years & Over     387254
                                      2013      7    60 & 61 Years      81527
                                      2013      6   55 to 59 Years      43785
                                      2013      2   18 to 24 Years     371666
                                      2013      0    Under 5 Years      12386

                                           Birthplace Moe
Geography                             Year
Boston-Cambridge-Newton, MA-NH        2017           1105
                                      2017           3761
                                      2017           3031
                                      2017           7067
                                      2017           3026
                                      2017           6990
                                      2017           2148
                                      2017           7318
                                      2017           3981
                                      2017           6990
                                      2017           5226
                                      2017           6580
                                      2017           5490
                                      2017           5982
                                      2017           6628
                                      2017           4204
                                      2017           5161
                                      2017           4034
                                      2017           4625
                                      2017           4376
                                      2017           1638
                                      2017           4738
                                      2017           3150
                                      2017           2640
                                      2017           1439
                                      2017           6164
                                      2017            998
                                      2017           5359
                                      2017            900
                                      2017           6888
...                                                   ...
New York-Newark-Jersey City, NY-NJ-PA 2013          12947
                                      2013           7321
                                      2013           7632
                                      2013           4409
                                      2013           4671
                                      2013          10609
                                      2013          10830
                                      2013           8191
                                      2013           8150
                                      2013           4117
                                      2013           6045
                                      2013          12295
                                      2013           4196
                                      2013           6295
                                      2013          14510
                                      2013           7352
                                      2013           3640
                                      2013           7020
                                      2013          14868
                                      2013           5197
                                      2013           7609
                                      2013           4685
                                      2013          10272
                                      2013          10427
                                      2013           7241
                                      2013           7564
                                      2013           4938
                                      2013           3697
                                      2013           9933
                                      2013           1757

[2200 rows x 6 columns]

In [156]:
dfproperty_tax=None
for name in property_tax:
    for i in range(30):
        dfproperty_tax=pd.concat([dfproperty_tax, pd.DataFrame.from_dict(property_tax[name][i],orient='index').T ])
dfproperty_tax=dfproperty_tax.drop('ID Geography',axis=1)
dfproperty_tax=dfproperty_tax.drop('Slug Geography',axis=1)
dfproperty_tax=dfproperty_tax.drop('ID Year',axis=1)
#reindex by location and year
dfproperty_tax=dfproperty_tax.set_index(['Geography','Year'])
dfproperty_tax

                                           ID Real Estate Taxes Paid  \
Geography                             Year
Boston-Cambridge-Newton, MA-NH        2017                         5
                                      2017                         0
                                      2017                         4
                                      2017                         1
                                      2017                         3
                                      2017                         2
                                      2016                         1
                                      2016                         5
                                      2016                         0
                                      2016                         3
                                      2016                         2
                                      2016                         4
                                      2015                         4
                                      2015                         0
                                      2015                         3
                                      2015                         2
                                      2015                         5
                                      2015                         1
                                      2014                         3
                                      2014                         4
                                      2014                         1
                                      2014                         5
                                      2014                         2
                                      2014                         0
                                      2013                         4
                                      2013                         5
                                      2013                         0
                                      2013                         1
                                      2013                         2
                                      2013                         3
...                                                              ...
New York-Newark-Jersey City, NY-NJ-PA 2017                         5
                                      2017                         0
                                      2017                         4
                                      2017                         1
                                      2017                         3
                                      2017                         2
                                      2016                         1
                                      2016                         5
                                      2016                         0
                                      2016                         3
                                      2016                         2
                                      2016                         4
                                      2015                         4
                                      2015                         0
                                      2015                         3
                                      2015                         2
                                      2015                         5
                                      2015                         1
                                      2014                         3
                                      2014                         4
                                      2014                         1
                                      2014                         5
                                      2014                         2
                                      2014                         0
                                      2013                         4
                                      2013                         5
                                      2013                         0
                                      2013                         1
                                      2013                         2
                                      2013                         3

                                               Real Estate Taxes Paid  \
Geography                             Year
Boston-Cambridge-Newton, MA-NH        2017  No Real Estate Taxes Paid
                                      2017             Less Than $800
                                      2017             $3,000 or More
                                      2017             $800 to $1,499
                                      2017           $2,000 to $2,999
                                      2017           $1,500 to $1,999
                                      2016             $800 to $1,499
                                      2016  No Real Estate Taxes Paid
                                      2016             Less Than $800
                                      2016           $2,000 to $2,999
                                      2016           $1,500 to $1,999
                                      2016             $3,000 or More
                                      2015             $3,000 or More
                                      2015             Less Than $800
                                      2015           $2,000 to $2,999
                                      2015           $1,500 to $1,999
                                      2015  No Real Estate Taxes Paid
                                      2015             $800 to $1,499
                                      2014           $2,000 to $2,999
                                      2014             $3,000 or More
                                      2014             $800 to $1,499
                                      2014  No Real Estate Taxes Paid
                                      2014           $1,500 to $1,999
                                      2014             Less Than $800
                                      2013             $3,000 or More
                                      2013  No Real Estate Taxes Paid
                                      2013             Less Than $800
                                      2013             $800 to $1,499
                                      2013           $1,500 to $1,999
                                      2013           $2,000 to $2,999
...                                                               ...
New York-Newark-Jersey City, NY-NJ-PA 2017  No Real Estate Taxes Paid
                                      2017             Less Than $800
                                      2017             $3,000 or More
                                      2017             $800 to $1,499
                                      2017           $2,000 to $2,999
                                      2017           $1,500 to $1,999
                                      2016             $800 to $1,499
                                      2016  No Real Estate Taxes Paid
                                      2016             Less Than $800
                                      2016           $2,000 to $2,999
                                      2016           $1,500 to $1,999
                                      2016             $3,000 or More
                                      2015             $3,000 or More
                                      2015             Less Than $800
                                      2015           $2,000 to $2,999
                                      2015           $1,500 to $1,999
                                      2015  No Real Estate Taxes Paid
                                      2015             $800 to $1,499
                                      2014           $2,000 to $2,999
                                      2014             $3,000 or More
                                      2014             $800 to $1,499
                                      2014  No Real Estate Taxes Paid
                                      2014           $1,500 to $1,999
                                      2014             Less Than $800
                                      2013             $3,000 or More
                                      2013  No Real Estate Taxes Paid
                                      2013             Less Than $800
                                      2013             $800 to $1,499
                                      2013           $1,500 to $1,999
                                      2013           $2,000 to $2,999

                                           Real Estate Taxes by Mortgage  \
Geography                             Year
Boston-Cambridge-Newton, MA-NH        2017                         15776
                                      2017                         18774
                                      2017                        941114
                                      2017                         36647
                                      2017                         86085
                                      2017                         28980
                                      2016                         37106
                                      2016                         17793
                                      2016                         18503
                                      2016                         92557
                                      2016                         30138
                                      2016                        909996
                                      2015                        888504
                                      2015                         15541
                                      2015                         98450
                                      2015                         31139
                                      2015                         17690
                                      2015                         39579
                                      2014                        115001
                                      2014                        839392
                                      2014                         44373
                                      2014                         29414
                                      2014                         31945
                                      2014                         27839
                                      2013                        826275
                                      2013                         23956
                                      2013                         25235
                                      2013                         46715
                                      2013                         36614
                                      2013                        111842
...                                                                  ...
New York-Newark-Jersey City, NY-NJ-PA 2017                        197804
                                      2017                         54309
                                      2017                       3172303
                                      2017                         78923
                                      2017                        168630
                                      2017                         61980
                                      2016                         84240
                                      2016                        174777
                                      2016                         61062
                                      2016                        181881
                                      2016                         71095
                                      2016                       3060497
                                      2015                       3032302
                                      2015                         57240
                                      2015                        195064
                                      2015                         70943
                                      2015                        171248
                                      2015                         94701
                                      2014                        207004
                                      2014                       2930962
                                      2014                        107348
                                      2014                        214473
                                      2014                         74262
                                      2014                         93047
                                      2013                       2936848
                                      2013                        220683
                                      2013                         84116
                                      2013                        108309
                                      2013                         88570
                                      2013                        216820

                                           Real Estate Taxes by Mortgage Moe
Geography                             Year
Boston-Cambridge-Newton, MA-NH        2017                           1661.47
                                      2017                            2194.9
                                      2017                           13147.7
                                      2017                           3185.28
                                      2017                           5115.53
                                      2017                           2520.41
                                      2016                           2754.54
                                      2016                           1927.39
                                      2016                           1948.83
                                      2016                           4116.65
                                      2016                           2738.56
                                      2016                           11249.6
                                      2015                           10078.9
                                      2015                           1826.43
                                      2015                           4852.44
                                      2015                           2468.23
                                      2015                           1661.77
                                      2015                           3319.05
                                      2014                            5328.7
                                      2014                           10520.7
                                      2014                           3042.96
                                      2014                           2422.56
                                      2014                           2763.33
                                      2014                              2420
                                      2013                           11552.6
                                      2013                           2143.71
                                      2013                            2320.7
                                      2013                            2727.6
                                      2013                            2628.2
                                      2013                           4540.08
...                                                                      ...
New York-Newark-Jersey City, NY-NJ-PA 2017                           7021.61
                                      2017                           3512.12
                                      2017                           22405.5
                                      2017                           4939.79
                                      2017                           6011.12
                                      2017                           3853.68
                                      2016                           4464.28
                                      2016                            6493.1
                                      2016                           4213.67
                                      2016                           6183.43
                                      2016                           4512.39
                                      2016                           19051.6
                                      2015                           21555.3
                                      2015                           3656.12
                                      2015                           6550.76
                                      2015                           3413.01
                                      2015                           6295.43
                                      2015                           4481.01
                                      2014                           6804.18
                                      2014                           20806.4
                                      2014                           4810.68
                                      2014                           6614.78
                                      2014                           4464.12
                                      2014                           3563.98
                                      2013                           21352.2
                                      2013                           6757.82
                                      2013                           3929.42
                                      2013                           4791.45
                                      2013                           4228.81
                                      2013                           7100.89

[300 rows x 4 columns]

In [161]:
dfcitizen=None
for name in citizen:
    for i in range(10):
        dfcitizen=pd.concat([dfcitizen, pd.DataFrame.from_dict(citizen[name][i],orient='index').T ])
dfcitizen=dfcitizen.drop('ID Geography',axis=1)
dfcitizen=dfcitizen.drop('Slug Geography',axis=1)
dfcitizen=dfcitizen.drop('ID Year',axis=1)
#reindex by location and year
dfcitizen=dfcitizen.set_index(['Geography','Year'])
dfcitizen

                                               ID Citizenship  Citizenship  \
Geography                                 Year
Boston-Cambridge-Newton, MA-NH            2017              0      Citizen
                                          2017              1  Non-Citizen
                                          2016              0      Citizen
                                          2016              1  Non-Citizen
                                          2015              0      Citizen
                                          2015              1  Non-Citizen
                                          2014              0      Citizen
                                          2014              1  Non-Citizen
                                          2013              0      Citizen
                                          2013              1  Non-Citizen
Atlanta-Sandy Springs-Roswell, GA         2017              0      Citizen
                                          2017              1  Non-Citizen
                                          2016              0      Citizen
                                          2016              1  Non-Citizen
                                          2015              0      Citizen
                                          2015              1  Non-Citizen
                                          2014              0      Citizen
                                          2014              1  Non-Citizen
                                          2013              0      Citizen
                                          2013              1  Non-Citizen
Miami-Fort Lauderdale-West Palm Beach, FL 2017              0      Citizen
                                          2017              1  Non-Citizen
                                          2016              0      Citizen
                                          2016              1  Non-Citizen
                                          2015              0      Citizen
                                          2015              1  Non-Citizen
                                          2014              0      Citizen
                                          2014              1  Non-Citizen
                                          2013              0      Citizen
                                          2013              1  Non-Citizen
...                                                       ...          ...
Chicago-Naperville-Elgin, IL-IN-WI        2017              0      Citizen
                                          2017              1  Non-Citizen
                                          2016              0      Citizen
                                          2016              1  Non-Citizen
                                          2015              0      Citizen
                                          2015              1  Non-Citizen
                                          2014              0      Citizen
                                          2014              1  Non-Citizen
                                          2013              0      Citizen
                                          2013              1  Non-Citizen
Los Angeles-Long Beach-Anaheim, CA        2017              0      Citizen
                                          2017              1  Non-Citizen
                                          2016              0      Citizen
                                          2016              1  Non-Citizen
                                          2015              0      Citizen
                                          2015              1  Non-Citizen
                                          2014              0      Citizen
                                          2014              1  Non-Citizen
                                          2013              0      Citizen
                                          2013              1  Non-Citizen
New York-Newark-Jersey City, NY-NJ-PA     2017              0      Citizen
                                          2017              1  Non-Citizen
                                          2016              0      Citizen
                                          2016              1  Non-Citizen
                                          2015              0      Citizen
                                          2015              1  Non-Citizen
                                          2014              0      Citizen
                                          2014              1  Non-Citizen
                                          2013              0      Citizen
                                          2013              1  Non-Citizen

                                               Citizenship Status
Geography                                 Year
Boston-Cambridge-Newton, MA-NH            2017            4385597
                                          2017             450934
                                          2016            4356130
                                          2016             438317
                                          2015            4352926
                                          2015             421395
                                          2014            4323719
                                          2014             408442
                                          2013            4289268
                                          2013             395031
Atlanta-Sandy Springs-Roswell, GA         2017            5430193
                                          2017             452257
                                          2016            5334808
                                          2016             455402
                                          2015            5265746
                                          2015             443985
                                          2014            5186771
                                          2014             425058
                                          2013            5089192
                                          2013             435501
Miami-Fort Lauderdale-West Palm Beach, FL 2017            5075483
                                          2017            1083341
                                          2016            5015633
                                          2016            1050754
                                          2015            4939790
                                          2015            1072541
                                          2014            4896870
                                          2014            1032949
                                          2013            4797269
                                          2013            1030922
...                                                           ...
Chicago-Naperville-Elgin, IL-IN-WI        2017            8699755
                                          2017             834140
                                          2016            8684197
                                          2016             828771
                                          2015            8678437
                                          2015             871671
                                          2014            8713130
                                          2014             840680
                                          2013            8650516
                                          2013             886524
Los Angeles-Long Beach-Anaheim, CA        2017           11264995
                                          2017            2088912
                                          2016           11157994
                                          2016            2152453
                                          2015           11130202
                                          2015            2209866
                                          2014           11030350
                                          2014            2231870
                                          2013           10904442
                                          2013            2226989
New York-Newark-Jersey City, NY-NJ-PA     2017           17726440
                                          2017            2594436
                                          2016           17517182
                                          2016            2636452
                                          2015           17571796
                                          2015            2610509
                                          2014           17455983
                                          2014            2636900
                                          2013           17315091
                                          2013            2634411

[100 rows x 3 columns]

In [164]:
dflocal=None
for name in local:
    for i in range(5):
        dflocal=pd.concat([dflocal, pd.DataFrame.from_dict(local[name][i],orient='index').T ])
dflocal=dflocal.drop('ID Geography',axis=1)
dflocal=dflocal.drop('Slug Geography',axis=1)
dflocal=dflocal.drop('ID Year',axis=1)
#reindex by location and year
dflocal=dflocal.set_index(['Geography','Year'])
dflocal

C:\Users\aleja\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  after removing the cwd from sys.path.

                                                  Foreign-Born Citizens  \
Geography                                    Year
Boston-Cambridge-Newton, MA-NH               2017                869620
                                             2016                838257
                                             2015                816401
                                             2014                   NaN
                                             2013                   NaN
Atlanta-Sandy Springs-Roswell, GA            2017                777555
                                             2016                753532
                                             2015                743009
                                             2014                   NaN
                                             2013                   NaN
Miami-Fort Lauderdale-West Palm Beach, FL    2017               2406964
                                             2016               2334438
                                             2015               2278878
                                             2014                   NaN
                                             2013                   NaN
Washington-Arlington-Alexandria, DC-VA-MD-WV 2017               1377375
                                             2016               1340621
                                             2015               1315879
                                             2014                   NaN
                                             2013                   NaN
Philadelphia-Camden-Wilmington, PA-NJ-DE-MD  2017                638538
                                             2016                622091
                                             2015                609314
                                             2014                   NaN
                                             2013                   NaN
Houston-The Woodlands-Sugar Land, TX         2017               1538097
                                             2016               1485232
                                             2015               1438555
                                             2014                   NaN
                                             2013                   NaN
Dallas-Fort Worth-Arlington, TX              2017               1285103
                                             2016               1238622
                                             2015               1206741
                                             2014                   NaN
                                             2013                   NaN
Chicago-Naperville-Elgin, IL-IN-WI           2017               1689797
                                             2016               1682220
                                             2015               1693807
                                             2014                   NaN
                                             2013                   NaN
Los Angeles-Long Beach-Anaheim, CA           2017               4433826
                                             2016               4425953
                                             2015               4436626
                                             2014                   NaN
                                             2013                   NaN
New York-Newark-Jersey City, NY-NJ-PA        2017               5825675
                                             2016               5749207
                                             2015               5720729
                                             2014                   NaN
                                             2013                   NaN

                                                  Population
Geography                                    Year
Boston-Cambridge-Newton, MA-NH               2017    4836531
                                             2016    4794447
                                             2015    4774321
                                             2014    4732161
                                             2013    4684299
Atlanta-Sandy Springs-Roswell, GA            2017    5882450
                                             2016    5790210
                                             2015    5709731
                                             2014    5611829
                                             2013    5524693
Miami-Fort Lauderdale-West Palm Beach, FL    2017    6158824
                                             2016    6066387
                                             2015    6012331
                                             2014    5929819
                                             2013    5828191
Washington-Arlington-Alexandria, DC-VA-MD-WV 2017    6216710
                                             2016    6133552
                                             2015    6098283
                                             2014    6032744
                                             2013    5950214
Philadelphia-Camden-Wilmington, PA-NJ-DE-MD  2017    6096120
                                             2016    6070500
                                             2015    6069875
                                             2014    6051170
                                             2013    6034678
Houston-The Woodlands-Sugar Land, TX         2017    6892427
                                             2016    6772470
                                             2015    6656946
                                             2014    6490180
                                             2013    6313158
Dallas-Fort Worth-Arlington, TX              2017    7400479
                                             2016    7232599
                                             2015    7102165
                                             2014    6954003
                                             2013    6812373
Chicago-Naperville-Elgin, IL-IN-WI           2017    9533895
                                             2016    9512968
                                             2015    9550108
                                             2014    9553810
                                             2013    9537040
Los Angeles-Long Beach-Anaheim, CA           2017   13353907
                                             2016   13310447
                                             2015   13340068
                                             2014   13262220
                                             2013   13131431
New York-Newark-Jersey City, NY-NJ-PA        2017   20320876
                                             2016   20153634
                                             2015   20182305
                                             2014   20092883
                                             2013   19949502